name: outputs
on: 
  push:
    branches:
     - main
  workflow_dispatch:
   

jobs:
  job1:
    name: job1-name  
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test1 }}
      output3: ${{ steps.step3.outputs.val }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test1=world!" >> "$GITHUB_OUTPUT"
      - id: step3
        run: echo "val=another variable" >> $GITHUB_OUTPUT
  job2:
    name: job2-name  
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
          OUTPUT3: ${{needs.job1.outputs.output3}}

        run: | 
            echo "${{needs.job1.outputs.output1}}"
            echo "${{needs.job1.outputs.output2}}"
            echo "${{needs.job1.outputs.output3}}"